Skills/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.Homepage.as_view(), name='home'),
    #/contact
    url(r'^contact/$',views.Contact_team.as_view(), name='contact_team'),

    #/accounts/login
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    #accounts/logout
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.Test.as_view(), name='test'),
    url(r'^thanks/$', views.Thanks.as_view(), name='thanks')
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view

from . import views

app_name = 'accounts'
urlpatterns = [

url(r'^login/$',auth_view.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
url(r'^logout/$',auth_view.LogoutView.as_view(), name= 'logout'),
url(r'^signup/$', views.SignUp.as_view(), name ='School_signup'),          
   
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your model.

class User(auth.models.User, auth.models.PermissionsMixin, models.Model):

    Register_no = models.IntegerField(unique=True)
    school_name = models.CharField(max_length=200, blank=False)
    RAJASTHAN = 'RA'
    HARIYANA = 'HY'
    GUJARAT = 'GUJ'
    MAHARASHTRA = 'MHR'
    UTTRA_PRADESH = 'UP'
    MADHAYA_PRADESH = 'MP'
    HIMACHAL = 'HIM'

    CHOICES_IN_STATES = (
    	(RAJASTHAN , 'Rajasthan'),
    	(HARIYANA ,'Hariyana'),
    	(GUJARAT ,'Gujarat'),
    	(MAHARASHTRA , 'Maharashtra'),
    	(UTTRA_PRADESH , 'Utra Pradesh'),
    	(MADHAYA_PRADESH , 'Madhaya Pradesh'),
    	(HIMACHAL , 'Himachal Pradesh'),
	)

    state = models.CharField(max_length=50,blank=False, choices = CHOICES_IN_STATES, default = 'Rajasthan')
    village = models.CharField(max_length=100, blank=False)
    created_at = models.DateTimeField(auto_now =True)

    def __str__(self):
        return "@{}".format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


# for signup new user with help of UserCreationForm
class UserForm(UserCreationForm):
    Register_no = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('Register_no', 'school_name', 'username', 'email' , 'state', 'village', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.Register_no = self.cleaned_data['Register_no']
        user.school_name = self.cleaned_data['school_name']
        user.state = self.cleaned_data['state']
        user.village = self.cleaned_data['village']

        if commit:
           user.save()


def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].label = "Enter name here"
    self.fields['email'].label = "Enetr email"
    self.fields['password'].label = "Enter Password"

Skills/views.py
from django.views.generic import TemplateView


class Homepage(TemplateView):
    template_name = 'index.html'


class Test(TemplateView):
    template_name = 'test.html'


class Thanks(TemplateView):
    template_name = 'thanks.html'


class Contact_team(TemplateView):
    template_name = 'contact.html'

accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from . import forms


# Create your views here.
class SignUp(CreateView):
	form_class = forms.UserForm
	success_url = reverse_lazy('login')
	template_name = 'accounts/signup.html'

accounts/templates/accounts/login.html
{% extends 'base.html '%}
{% load bootstrap3 %}
{% block title_block %}School login{% endblock %}
{% block loginContent %}


<section class="container">
   <div class="bg-text">
       <h2>Login as schools Authority</h2>
       <form method="POST">
       	   {% csrf_token %}
       	   {% bootstrap_form form %}
       	   <input type="submit" class="btn btn-default"  value="Login">

       </form>
   </div>
</section>




<section class="container">
 <div class="bg-text">
 <h2>login as Person</h2> 
	<form method="POST">
		{% csrf_token %}
		{% bootstrap_form form%}
		 <input type="submit" class="btn btn-default"  value="Login">
	</form>
</div>
</section>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html '%}
{% load bootstrap3 %}
{% block title_block %}School Registration {% endblock %}
{% block signupContent %}

   <div class="container">
       <h2>Register your Schools Authority</h2>
       <form method="POST">
       	   {% csrf_token %}
       	   {% bootstrap_form form %}
{#       	   <input type="submit" class="btn btn-default"  value="Sign up">#}
           <button type="submit" class="btn btn-primary active btn-block" >Sign up</button>
           <p class="fa-align-center">Alredy have an account?
           <a href="{% url 'accounts:login' %}" class="btn btn-default">Login here</a>
           </p>
       </form>
   </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="en">
<head>
     <title>{% block title_block %}Title{% endblock %}</title>

     <!--  require meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- load all bootstrap files -->
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type="text/css">
     <link rel="stylesheet" type="text/css" href="{% static  'Skills/CSS/base_file.css'%}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->

</head>
<body>

<!-- top nav bar of webiste -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<li class="nav-item active">
  <a class="navbar-brand" href="{% url 'home' %}">
  {% load static %}
    <img src="{% static 'Skills/Images/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
   Indian Sports Search
  </a>
  </li>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      
        <a class="nav-link" href="#">Quiz<span class="sr-only">(current)</span></a>
      
      <li class="nav-item">
        <a class="nav-link" href="#">Featured</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="#">News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact_team' %}">Conatct</a>
      </li>

    </ul>

    <!-- Right side comtent -->
        <!-- dropdown regitration page for different commuity -->
    <div class="dropdown show">
    {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
               <form class="form-inline my-2 my-lg-0">
               <input class="form-control mr-sm-2" type="search" placeholder="Search any sports" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
               </form>
              &nbsp;
              <li><a class="btn btn-danger" href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>

    {% else %}
     <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Register
     </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item" href="#">Community Registration</a>
      <a class="dropdown-item" href="{% url 'accounts:School_signup' %}">School Registration</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Simple Register</a>
  </div>
</div>
&nbsp;
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search any sports" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    &nbsp;
    <a class="btn btn-info btn-md" href="{% url 'accounts:login' %}">
    Login
    </a>
    {% endif %}
  </div>

</nav>
</nav>
<!-- end of top nav bar -->




<!-- template of index file -->
{% block content %}
{% endblock %}


<!-- template of contact file -->
{% block contect %}
{% endblock %}

<!-- template of User signup form -->
{% block signupContent %}
{% endblock %}

<!-- tmeplate of user login form -->
{% block loginContent %}
{% endblock %}

<!-- <div class="navbar navbar-inverse">
    <footer class="container-fluid bg-2 text-center">
  <center><p>Website Design and Developed  By Team<a href=""><strong>@H<sup>3</sup></strong>Hardik Dadhich</center></a></p> 
</footer>
</div> -->
<footer>

  <nav class="navbar navbar-expand-lg navbar-light fixed-bottom" id="mainNav"  style="background-color: rgba(0,0, 0, 10); ">
      <div class="container" style="text-transform: capitalize; ">
        <a class="navbar-brand" href="{% url 'contact_team' %}" style="color: white">Meet Developers</a>
       
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#bnavbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Base Menu
          <i class="fa fa-bars"></i>
        </button>
        
        <div class="collapse navbar-collapse" id="bnavbarResponsive">
          <ul class="navbar-nav ml-auto">
           
            <li class="nav-item">
              <a class="nav-link " href="#" style="color: white">Disclaimer</a>
            </li>

            <li class="nav-item">
              <a class="nav-link " href="#" style="color: white">Privacy Policy</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="#" style="color: white">Terms Of Service</a>
            </li>
       
           
 
             
          </ul>
        </div>
      </div>

    </nav>
      <div class="container text-center">
        <p style="color: black: White">Copyright &copy; 2018 @H<sup>3</sup> Teams</p>

      </div>


      
    </footer>



</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title_block %}Contact develper{% endblock %}
{% load staticfiles %}  
  <!-- <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 -->

{% block contect %}

  <style>

  /*body content css starts here*/
  body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
  .margin {margin-bottom: 45px;}
  .bg-1 { 
      background-color: #1abc9c; /* Green */
      color: #ffffff;
  }
  .bg-2 { 
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
  .bg-3 { 
      background-color: #ffffff; /* White */
      color: #555555;
  }
  .bg-4 { 
      background-color: #d1ac00; /* Black Gray */
      color: #fff;
  }
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }
/*  body content css ends here*/

/*social media bar css*/
  .fa {
  padding: 20px;
  font-size: 30px;
  width: 50px;
  text-align: center;
  text-decoration: none;
  margin: 5px 2px;
}

.fa:hover {
    opacity: 0.7;
}

.fa-facebook {
  background: #3B5998;
  color: white;
}

.fa-linkedin {
  background: #007bb5;
  color: white;
}

.fa-google {
  background: #dd4b39;
  color: white;
}
/*social meadia css ended here*/
  </style>
</head>



<!-- First Container -->
<div class="container-fluid bg-1 text-center">
  <h3 class="margin">Hardik Dadhich</h3>
  <img src="{% static 'Skills/Images/hardik.png' %}" class="img-responsive img-circle margin" style="display:inline" alt="Bird" width="350" height="350">
    <p>Hi , I am Full Stack Django Developer and Founder of Tech Leading Comapany <strong>H<sup>3</sup></strong>. I am Tech-Enthusiast,Developer and Travelling Lover.Currently I am Working with my team on making Human life more Easier with new Tech Solution. </p>
    <p>Do Support And Be with us!</p>
    <h3>I'm an Entreprenure</h3>
    <div class="row">
        <div class="list inline">

          <a href="#" class="fa fa-facebook"></a>
          <a href="#" class="fa fa-linkedin"></a>
          <a href="#" class="fa fa-google"></a>
       </div>
    </div>

</div>

<!-- Second Container -->
<div class="container-fluid bg-2 text-center">
  <h3 class="margin">Avinash jain</h3>
  <img src="" class="img-responsive img-circle margin" style="display:inline" alt="Bird" width="350" height="350">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
  <h3>I'm an Developer</h3>
  <div class="row">
    <ul class="list inline">

    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-linkedin"></a>
    <a href="#" class="fa fa-google"></a>
   </ul>

    </div>
</div>

<!-- Third Container (Grid) -->
<!-- <div class="container-fluid bg-3 text-center">    
  <h3 class="margin">Where To Find Me?</h3><br>
  <div class="row">
    <div class="col-sm-4">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <img src="birds1.jpg" class="img-responsive margin" style="width:100%" alt="Image">
    </div>
    <div class="col-sm-4"> 
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <img src="birds2.jpg" class="img-responsive margin" style="width:100%" alt="Image">
    </div>
    <div class="col-sm-4"> 
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <img src="birds3.jpg" class="img-responsive margin" style="width:100%" alt="Image">
    </div>
  </div>
</div> -->


<!-- third container -->
<div class="container-fluid bg-3 text-center">
  <h3 class="margin">Atul Goyal</h3>
  <img src="" class="img-responsive img-circle margin" style="display:inline" alt="Bird" width="350" height="350">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
  <h3>I'm an developer</h3>
  <div class="row">
    <ul class="list inline margin">

    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-linkedin"></a>
    <a href="#" class="fa fa-google"></a>
   </ul>

    </div>
</div>


<!-- fourth section -->

<div class="container-fluid bg-4 text-center">
  <h3 class="margin">Abhijeet Yadav</h3>

  <img src="" class="img-responsive img-circle margin" style="display:inline" alt="Bird" width="350" height="350">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
  <h3>I'm an Developer</h3>
<div class="row">
    <ul class="list inline">

    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-linkedin"></a>
    <a href="#" class="fa fa-google"></a>
   </ul>

    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html'%}
{% load bootstrap3 %}


{% block content %}
<h1>hello from here</h1>
<section class="content-section text-center"> </section>
<div class="container">
    <div class="row">
       <div class="col-lg-8 mx-auto">
          <div class="videoWrapper col-lg-12">
            <iframe src="https://www.youtube.com/embed/112E0fMX3vk" frameborder="0" allowfullscreen=""></iframe>
          
          </div>
        </div>  
    </div>
</div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    {% if user.is_authenticated %}

    <h1>welcome back!<a href="">{{ user.username }}</a></h1>
    {% else %}
    <h2>login failed</h2>
    {% endif %}
    </div>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <h1>Thanks For Visting your accounts!</h1>
    </div>
{% endblock %}